version: "3.7"
services:
  metabase:
    env_file:
      - .env
    container_name: metabase
    image: ${MB_IMAGE}
    ports:
      - "${MB_HOSTPORT}:${MB_PORT}"
    depends_on:
      - postgres_warehouse
    links:
      - postgres_warehouse

  postgres_warehouse:
    env_file:
      - .env
    container_name: postgres_warehouse
    image: "postgres:11"
    ports:
      - "${PGHOSTPORT}:${PGPORT}"
    volumes:
      - ./init_postgresdb.sh:/docker-entrypoint-initdb.d/init_postgresdb.sh
      - "${WAREHOUSE_DATA}:/var/lib/postgresql/data"
