#!/bin/bash set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<- EOSQL
CREATE USER $WAREHOUSE_USER WITH password '$WAREHOUSE_PASSWORD';
CREATE USER $MB_DB_USER WITH password '$MB_DB_PASS';
CREATE DATABASE $MB_DB_DBNAME;
GRANT ALL PRIVILEGES ON DATABASE $MB_DB_DBNAME TO $MB_DB_USER;
ALTER USER $WAREHOUSE_USER WITH CREATEDB;
EOSQL
